oomoxicons:
  # This changes depending on your iconset
  command: "oomox-archdroid-icons-cli"
  # Path to the desired theme you want to apply
  themepath: "/opt/oomox/scripted_colors/xresources/xresources-reverse"

oomoxgtk:
  # Path to the desired theme you want to apply
  themepath: "/opt/oomox/scripted_colors/xresources/xresources-reverse"

# oomoxspotify:
#   spotifypath: "/opt/spotify/Apps"
#   enabled: "True"

# slickpywal:
  # path:

# pywalneopixels:
  # path:

# waldiscord:
  # path:

# razer-cli:
  # path:

# telegrampalletegen:
  # path:

# spicetify:
  # path:

# pywalfox:
  # path:


zathura:
  path: "/home/hashedupforyou101/.config/zathura"

zathura-pywal:
  path: "/home/hashedupforyou101/Singularis/third-party-tools/zathura-pywal"


xfce4-terminal:
  path: "/home/hashedupforyou101/.config/xfce4/terminal"

xfce4-pywal:
  path: "/home/hashedupforyou101/Singularis/third-party-tools/xfce4-pywal"


dunst:
  path: "/home/hashedupforyou101/.config/dunst"

dunst-pywal:
  path: "/home/hashedupforyou101/Singularis/third-party-tools/dunst-pywal"


dwm:
  path: "/home/hashedupforyou101/.config/dwm/dwm-config"


xmenu:
  path: "/home/hashedupforyou101/Singularis/aspects/xmenu"

starttree:
  path: "/home/hashedupforyou101/Singularis/third-party-tools/start-tree"
