#!/usr/bin/bash

cat <<EOF
oomoxicons:
  # This changes depending on your iconset
  command: "oomox-archdroid-icons-cli"
  # Path to the desired theme you want to apply
  themepath: "/opt/oomox/scripted_colors/xresources/xresources-reverse"

oomoxgtk:
  # Path to the desired theme you want to apply
  themepath: "/opt/oomox/scripted_colors/xresources/xresources-reverse"

oomoxspotify:
  spotifypath: "/opt/spotify/Apps"
  enabled: True

# slickpywal:
#   path:

# pywalneopixels:
#   path:

# razercli:
#   path:

# telegrampalletegen:
#   path: ""

# spicetify:
#   path:

pywalfox:
  enable: True

waldiscord:
  path: "$HOME/.local/share/Singularis/third-party-tools/wal-discord"

xmenu:
  path: "$HOME/.config/xmenu"

starttree:
  path: "$HOME/.local/share/Singularis/third-party-tools/start-tree"

gnuplot:
  path: "$HOME/.local/share/Singularis/third-party-tools/gnuplot-pywal"

xfce4-terminal:
  path: "$HOME/.config/xfce4"
EOF
